### ISSUE TITLE
Permission denied on lumen.log writing

### ISSUE THREAD

**Issue by leckylao** [saada/docker-lumen#12]
From a scratch success build run gets:

> Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/html/storage/logs/lumen.log" could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 

And I run 

> docker-compose exec php ps -aux
> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root         1  0.0  0.9 135220 18816 ?        Ss   04:56   0:00 php-fpm: master process (/usr/local/etc/
> www-data     5  0.0  0.6 135624 12552 ?        S    04:56   0:00 php-fpm: pool www
> www-data     6  0.0  0.6 135624 12552 ?        S    04:56   0:00 php-fpm: pool www

So php is running ww-data

Then I run
```
docker-compose exec php ls -la /var/www/html/storage
total 0
drwxr-xr-x 1 1000 staff 102 Jun 22 04:36 .
```
So the folder is own by staff. Which caused the permission issue

My current solution is 
- Remove volume from docker-compose in php
- at the end of php/Dockerfile adds 
COPY ./ /var/www/html
RUN chown -R www-data:www-data /var/www/html

**Comment by leckylao** [comment]
One issue is without volume the code doesn’t automatic update. But seems the design of volume doesn’t allow modifying the files from inside the docker, so a trade-off.

**Comment by saada** [comment]
Hey @leckylao 

Thanks for reporting that issue.
This is a known docker-ism. One thing we could do is set the container uid to match the host machine's from inside the `docker-compose.yml` file.

```yml
service1:
  user: "$UID:$GID"
  ...
```

Can you please test that and make a PR accordingly?
Thanks!

**Comment by leckylao** [comment]
Hi @saada, that user variable works.  So what I did is checking the files belong to which user

> docker-compose exec php ls -la /var/www/html
total 112
drwxr-xr-x 1 1000 staff   442 Jun 30 12:06 .
drwxr-xr-x 4 root root   4096 Jun 30 12:06 ..
-rw-r--r-- 1 1000 staff 12288 Jun 30 12:06 .Dockerfile.swp
-rw-r--r-- 1 1000 staff   310 Jun 30 12:06 Dockerfile

and adding 

`user: “1000”`

this way you will see the process runs with the same user

```
docker-compose exec php ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000         1  1.7  0.8 123512 17136 ?        Ss   12:09   0:00 php-fpm: master
1000         5  0.0  0.3 123512  7944 ?        S    12:09   0:00 php-fpm: pool w
1000         6  0.0  0.3 123512  7944 ?        S    12:09   0:00 php-fpm: pool w
1000         7  0.0  0.0  17500  2012 ?        Rs+  12:09   0:00 ps -aux
```

The other way is using environment variable

export UID
and set
`user: “${UID}”`

**Comment by saada** [comment]
awesome!
I'll go ahead and close this issue. You could still submit a PR if you like.
Thank you
