### ISSUE TITLE
nginx.conf /var/www/html/public does not exist (on Mac)

### ISSUE THREAD

**Issue by openrory** [saada/docker-lumen#15]
First of all, you're doing great work. These linked containers helped me out a lot, because they allow me to work locally and (in the future) setup continuous integration. I noticed one issue, however.

Maybe it's me working on a Mac (although this should not be an issue when using Docker), but the folder `/var/www/html/public` in `nginx.conf` does not exist in container `php`. As a result, the browser returns 'File not found.' when I browse to localhost:80 (or 8080 in my case), since the nginx container tries to search for a file `index.php` in container `php` for a folder `/var/www/html/public`, which does not exist.  

I tried several solutions, and this worked for me: `/var/www/app/public` does exist, so I recommend replacing 'html' by 'app'. Otherwise, changing `lumen new app` to `lumen new html` may be a solution, but I did not test that yet.

**Comment by saada** [comment]
thanks for your PR #14
