### ISSUE TITLE
alairock/lumen no longer exists

### ISSUE THREAD

**Issue by josevavia** [saada/docker-lumen#16]
I am trying to start a project with this package, but the `Create Lumen App` step fails:

```
Unable to find image 'alairock/lumen:latest' locally
docker: Error response from daemon: pull access denied for alairock/lumen, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

I thing that the package `alairock/lumen` is no longer available

**Comment by itwasmattgregg** [comment]
I am also having this issue.

**Comment by saada** [comment]
Hey @josevavia , @itwasmattgregg , thanks for reporting this issue.
I went ahead and resolved it by uploading my own docker image.
https://github.com/saada/docker-lumen/commit/3f72a7863bc0b64e76c04527aaa5125e15d00fe6
