### ISSUE TITLE
Getting Error E: Unable to locate package php5-memcached

### ISSUE THREAD

**Issue by krisalcordo** [saada/docker-lumen#18]
I get error below when I run `docker-compose up --build -d`

Thanks!

```ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get install -y php5-memcached     && docker-php-ext-install mcrypt mbstring tokenizer mysqli pdo_mysql     && apt-get install -y libz-dev libmemcached-dev     && pecl install memcached     && echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini' returned a non-zero code: 100```

**Comment by saada** [comment]
Hey thanks for reporting!
Please pull the latest changes and try again.

**Comment by krisalcordo** [comment]
Thank you!
