### ISSUE TITLE
Getting Fatal Error

### ISSUE THREAD

**Issue by 0xmaayan** [saada/docker-lumen#19]
Hey, getting this error after running

docker-compose up --build -d

and browsing to [http://localhost:80/](http://localhost:80/)

```
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/app/vendor/symfony/debug/Exception/FlattenException.php on line 41

Fatal error: Exception thrown without a stack frame in Unknown on line 0

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/app/vendor/symfony/debug/Exception/FlattenException.php on line 41

Fatal error: Exception thrown without a stack frame in Unknown on line 0
```

Also tried to change the port (80) but got the same error.

**Comment by saada** [comment]
Hey @msbir , thanks for reporting!
https://github.com/saada/docker-lumen/commit/848da4a61c5779e4d489bfd3a6f4b561f10cc60b should resolve this.
Please pull the latest change and try again.
Thank you
