### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by rfdss** [saada/docker-lumen#23]
I am having problems with the error message "File not found". I have tried to change the path to: /var/www/html/app/public, /var/www/html/public, /var/www/html, but none of them works.

**Comment by vladshut** [comment]
How did you fix this issue?

**Comment by ivan-avalos** [comment]
X2. Please.

**Comment by karlkras** [comment]
@rafaeldevs Yes Rafael, how did you fix this? I'm just running the base example out of the box and getting this error. What file isn't getting found?

**Comment by saada** [comment]
I'll go ahead and reopen this until it's resolved

**Comment by saada** [comment]
This is now fixed in the latest merge. Thanks for reporting
