### ISSUE TITLE
How would you run artisan commands ?

### ISSUE THREAD

**Issue by kareemashraf** [saada/docker-lumen#26]
Hi, so im using Laravel migrations for the database 
how can i run "php artisan migrate" command on dockerfile ?

Thanks.

**Comment by saada** [comment]
Closed by https://github.com/saada/docker-lumen/commit/4884f6d705c5e8b250eecd7af11a4f287c53c0e2

Please check the new README. You'll need to set the `.env` files and then use the instructions for php artisan commands.

Cheers 😄
