### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by yuchiko** [saada/docker-lumen#3]
In default install lumen app i have some permission errors when i am trying to save my view files

I fix this by this command:
`chmod 777 -R /storage`

But i have a new error, nginx/docker/lumen doesn't see my assets files (css/images/js) in public folder

P.S:: routing works perfectly
## For example i have these:

**/images/php/app/app/Http/routes.php**

``` php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

$app->get('/', function () use ($app) {
    return view('index');
});

$app->get('instruction', function () use ($app) {
    return view('instruction');
});

$app->get('cart/get', 'CartController@get');

$app->get('newsletter/subscribe', 'NewsletterController@subscribe');
```

**/images/php/app/resources/views/instruction.blade.php**

``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet"
            href="instruction-assets/bootstrap.min.css">
    </head>
    <body>
        <div class="container-test">
            <div>
                <img src="img/products/bag.jpg">
            </div>
        </div>
    </body>
</html>

```

_instruction-assets/bootstrap.min.css -> 404
img/products/bag.jpg -> 404_

**Comment by saada** [comment]
The first part is primarily a Docker issue.
The second one about the assets can be resolved with an nginx.conf and some volume mounting.
Feel free to write a pull request. I can also work on this when I get a chance.

**Comment by saada** [comment]
@Yuchiko , since these are all Virtualbox related errors, I updated the README to use docker for Mac/Windows/Linux which should not have permission issues. I tested it on my mac from scratch and everything works great.
