### ISSUE TITLE
Docker new version

### ISSUE THREAD

**Issue by comlaterra** [saada/docker-lumen#6]
I just updated docker to the latests versions, and somehow it stopped working, I just can't access to it. 

Can it be it is related to the Docker version?

Thanks

**Comment by saada** [comment]
@comlaterra can you please post an error log so I can help you debug this?
Which OS are you running?
Which version of Docker?

**Comment by saada** [comment]
@comlaterra I'm closing this since I haven't heard from you in 3 months

**Comment by comlaterra** [comment]
Hi @saada .

Sorry for not answering, somehow I missed the previous message.
If it happens again i promise to keep up and help as much as possible.

Thanks a lot anyway.

**Comment by saada** [comment]
Thank you!
