### ISSUE TITLE
Class 'Memcached' not found

### ISSUE THREAD

**Issue by franklincm** [saada/docker-lumen#7]
Hi, any artisan commands, i.e. `php artisan make:migration create_users_table`, produce the following:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Memcached' not found
```

**Comment by franklincm** [comment]
Disregard. Fix is to edit `/etc/php/conf.d/memcached.ini` and uncomment:
```
;extension=memcached.so
```

**Comment by franklincm** [comment]
For clarification, I had to add the following lines to `images/php/Dockerfile`:
```
RUN apt-get install -y libz-dev libmemcached-dev
RUN pecl install memcached
RUN echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini
```

**Comment by saada** [comment]
@gnullByte you can make a PR if you like
