### ISSUE TITLE
ERROR: for php  Cannot start service php: oci runtime error: no such file or directory

### ISSUE THREAD

**Issue by leckylao** [saada/docker-lumen#9]
Same issue as https://github.com/moby/moby/issues/26855.

Solution is changing from 
docker-compose.yml
`working_dir: /app/public `
to 
`working_dir: /var/www/app/public`

```
volumes:
    - ./images/php/app:/app
```
to 
```
volumes:
    - ./images/php/app:/var/www/app
```

And nginx.conf
`root /app/public;`
to
`root /var/www/app/public;`
Hope that helps.

**Comment by saada** [comment]
Thanks for reporting @leckylao. Feel free to make a PR :)
